### ISSUE TITLE
AA ignored in indexed RRGGBBAA write

### ISSUE THREAD

**Issue by raymondben** [coolbutuseless/spng#1]
Apologies if this is still on your list to address (but the README suggests that it should work, so I'll raise it): alpha is ignored when writing an indexed image, e.g.:
```
indices <- test_image$indexed$integer_index
palette <- test_image$indexed$palette
palette <- sub("FF$", "00", palette) ## make all colours fully transparent
tmp <- tempfile()
write_png(image = indices, palette = palette, file = tmp)
browseURL(tmp)
```
should be a fully transparent image, but it's fully opaque.

**Comment by coolbutuseless** [comment]
Good catch.

Vanilla indexed PNG's have a PLTE chunk which contains the palette.

But this palette is only RGB. No alpha.

{Fastpng} accepts palette colours specified as #rrggbb or #rrggbbaa, but currently throws away the alpha as there's no way to store it in the PLTE chunk.

The PNG standard allows for the encoding of the palette alpha in the tRNS chunk.

tRNS transparency is next on my list

**Comment by coolbutuseless** [comment]
@raymondben Please have a look at the new support for transparent indexed images when you have a chance.

Just a note that the 'tRNS' chunk is an optional chunk, so not all PNG readers may respect it.

I've also updated the `flags` argument in `read_png()` to always decode the `tRNS` chunk if available.

Thanks for the issue.

**Comment by raymondben** [comment]
Works a treat! Thanks!
